# Atuin
{{ $atVersion := .versions.atuin -}}
{{- $atTriple := "" -}}
{{- if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) -}}
  {{- $atTriple = "x86_64-unknown-linux-musl" -}}
{{- else if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `arm64`) -}}
  {{- $atTriple = "aarch64-unknown-linux-musl" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) -}}
  {{- $atTriple = "aarch64-apple-darwin" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `amd64`) -}}
  {{- $atTriple = "x86_64-apple-darwin" -}}
{{- else if eq .chezmoi.os `windows` -}}
  {{- $atTriple = "x86_64-pc-windows-msvc" -}}
{{- end }}
{{- $atChecksum := index .hashes.atuin (printf "%s_%s" .chezmoi.os .chezmoi.arch) | default "" -}}

[".local/bin/atuin{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"]
    type = "archive-file"
    url = "https://github.com/atuinsh/atuin/releases/download/v{{ $atVersion }}/atuin-{{ $atTriple }}.{{ if eq .chezmoi.os `windows` }}zip{{ else }}tar.gz{{ end }}"
    path = "{{ if eq .chezmoi.os `windows` }}atuin.exe{{ else }}atuin-{{ $atTriple }}/atuin{{ end }}"
    executable = true
    {{ if $atChecksum -}}
    checksum.sha256 = "{{ $atChecksum }}"
    {{ end -}}
