# Herdr
{{ $herdrVersion := .versions.herdr -}}
{{- $herdrAsset := "" -}}
{{- if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) -}}
  {{- $herdrAsset = "herdr-linux-x86_64" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) -}}
  {{- $herdrAsset = "herdr-macos-aarch64" -}}
{{- end }}
{{- $herdrChecksum := index .hashes.herdr (printf "%s_%s" .chezmoi.os .chezmoi.arch) | default "" -}}

{{- if $herdrAsset }}

[".local/bin/herdr"]
    type = "file"
    url = "https://github.com/herdrdev/herdr/releases/download/v{{ $herdrVersion }}/{{ $herdrAsset }}"
    executable = true
    checksum.sha256 = "{{ $herdrChecksum }}"
{{- end }}

{{- if and (eq .chezmoi.os `windows`) (eq .chezmoi.arch `amd64`) }}
{{- $herdrWindowsUrl := printf "https://github.com/herdrdev/herdr/releases/download/v%s/herdr-windows-x86_64.zip" $herdrVersion -}}
{{- $herdrWindowsChecksum := .hashes.herdr.windows_amd64 -}}

[".local/bin/herdr.exe"]
    type = "archive-file"
    url = "{{ $herdrWindowsUrl }}"
    path = "herdr.exe"
    executable = true
    checksum.sha256 = "{{ $herdrWindowsChecksum }}"

[".local/bin/conpty"]
    type = "archive"
    url = "{{ $herdrWindowsUrl }}"
    exact = true
    stripComponents = 1
    include = ["conpty/**"]
    checksum.sha256 = "{{ $herdrWindowsChecksum }}"
{{- end }}
