# OpenCode
{{ $ocVersion := .versions.opencode -}}
{{- $ocFile := "" -}}
{{- if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) -}}
  {{- $ocFile = "opencode-linux-x64.tar.gz" -}}
{{- else if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `arm64`) -}}
  {{- $ocFile = "opencode-linux-arm64.tar.gz" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `amd64`) -}}
  {{- $ocFile = "opencode-darwin-x64-baseline.zip" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) -}}
  {{- $ocFile = "opencode-darwin-arm64.zip" -}}
{{- else if eq .chezmoi.os `windows` -}}
  {{- $ocFile = "opencode-windows-x64-baseline.zip" -}}
{{- end }}
{{- $ocChecksum := index .hashes.opencode (printf "%s_%s" .chezmoi.os .chezmoi.arch) | default "" -}}

[".local/bin/opencode{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"]
    type = "archive-file"
    url = "https://github.com/anomalyco/opencode/releases/download/v{{ $ocVersion }}/{{ $ocFile }}"
    path = "opencode{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"
    executable = true
    checksum.sha256 = "{{ $ocChecksum }}"
