{{ $rgVersion := .versions.ripgrep -}}
{{- $rgTriple := "" -}}
{{- if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) -}}
  {{- $rgTriple = "x86_64-unknown-linux-musl" -}}
{{- else if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `arm64`) -}}
  {{- $rgTriple = "aarch64-unknown-linux-gnu" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `amd64`) -}}
  {{- $rgTriple = "x86_64-apple-darwin" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) -}}
  {{- $rgTriple = "aarch64-apple-darwin" -}}
{{- else if eq .chezmoi.os `windows` -}}
  {{- $rgTriple = "x86_64-pc-windows-msvc" -}}
{{- end }}
{{- $rgChecksum := index .hashes.ripgrep (printf "%s_%s" .chezmoi.os .chezmoi.arch) | default "" -}}

[".local/bin/rg{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $rgVersion }}/ripgrep-{{ $rgVersion }}-{{ $rgTriple }}.{{ if eq .chezmoi.os `windows` }}zip{{ else }}tar.gz{{ end }}"
    path = "ripgrep-{{ $rgVersion }}-{{ $rgTriple }}/rg{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"
    executable = true
    checksum.sha256 = "{{ $rgChecksum }}"
