[".config/nvim"]
type = "git-repo"
url = "https://github.com/Xoffio/astrofile.git"
refreshPeriod = "24h"

[".local/share/nvim-app"]
type = "archive"
url = "https://github.com/neovim/neovim/releases/download/v{{ .versions.neovim }}/nvim-{{ if eq .chezmoi.os `darwin` }}macos{{ else }}linux{{ end }}-{{ if eq .chezmoi.arch `arm64` }}arm64{{ else }}x86_64{{ end }}.tar.gz"
exact = true
stripComponents = 1

[".local/bin/lazygit{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"]
type = "archive-file"
url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ .versions.lazygit }}/lazygit_{{ .versions.lazygit }}_{{ .chezmoi.os }}_{{ if eq .chezmoi.arch `arm64` }}arm64{{ else }}x86_64{{ end }}.{{ if eq .chezmoi.os `windows` }}zip{{ else }}tar.gz{{ end }}"
path = "lazygit{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"
executable = true
checksum.sha256 = "{{ if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) }}02beacbcda0fa342e50ae3480ba8147307353af3fb28e1d5f790e02329c201a6{{ else if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `arm64`) }}49abecdf6adf4f2dfdb11bf7b9bfada267ea523612ed809d1c6d87f6c04000a7{{ else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `amd64`) }}fde13daf583511aa24c42ca154911643231a5af784c7cdd8117264b2fc035b33{{ else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) }}65a367c6ea9a88efebaaf7998a6835eedb987e04916cef677264ff9b31b1b13e{{ end }}"

{{ $rgVersion := .versions.ripgrep -}}
{{- $rgTriple := "" -}}
{{- $rgChecksum := "" -}}
{{- if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) -}}
  {{- $rgTriple = "x86_64-unknown-linux-musl" -}}
  {{- $rgChecksum = "33e15bcf1624b25cdd2a55813a47a2f95dbe126268203e76aa6a585d1e7b149c" -}}
{{- else if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `arm64`) -}}
  {{- $rgTriple = "aarch64-unknown-linux-gnu" -}}
  {{- $rgChecksum = "a740b91c82eaf9914cfedd353572f2791cbe0162c84101ee0951058f4dcbc90d" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `amd64`) -}}
  {{- $rgTriple = "x86_64-apple-darwin" -}}
  {{- $rgChecksum = "af7825fcc69a2afc7a7aea55fc9af90e26421d8f20fe59df32e233c0b8a231c1" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) -}}
  {{- $rgTriple = "aarch64-apple-darwin" -}}
  {{- $rgChecksum = "3750b2e93f37e0c692657da574d7019a101c0084da05a790c83fd335bad973e4" -}}
{{- else if eq .chezmoi.os `windows` -}}
  {{- $rgTriple = "x86_64-pc-windows-msvc" -}}
  {{- $rgChecksum = "71b2fef860abe467217a538ff31de02f5258807c0129f771846f87bd029aafc5" -}}
{{- end }}

[".local/bin/rg{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $rgVersion }}/ripgrep-{{ $rgVersion }}-{{ $rgTriple }}.{{ if eq .chezmoi.os `windows` }}zip{{ else }}tar.gz{{ end }}"
    path = "ripgrep-{{ $rgVersion }}-{{ $rgTriple }}/rg{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"
    executable = true
    checksum.sha256 = "{{ $rgChecksum }}"

# OpenCode
{{ $ocVersion := .versions.opencode -}}
{{- $ocFile := "" -}}
{{- $ocChecksum := "" -}}
{{- if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `amd64`) -}}
  {{- $ocFile = "opencode-linux-x64.tar.gz" -}}
  {{- $ocChecksum = "3046e0404fdc60fb80307e7a47824ba07477364178a4d09baa8548496dd6d43b" -}}
{{- else if and (eq .chezmoi.os `linux`) (eq .chezmoi.arch `arm64`) -}}
  {{- $ocFile = "opencode-linux-arm64.tar.gz" -}}
  {{- $ocChecksum = "568461b7d4d8c19865c97e9a1102e613049c6039d01fe772154de873c1865840" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `amd64`) -}}
  {{- $ocFile = "opencode-darwin-x64-baseline.zip" -}}
  {{- $ocChecksum = "3888d74f1478b94ab1682a7c30942ab53e1266329f3786cf05e499381572dea8" -}}
{{- else if and (eq .chezmoi.os `darwin`) (eq .chezmoi.arch `arm64`) -}}
  {{- $ocFile = "opencode-darwin-arm64.zip" -}}
  {{- $ocChecksum = "fa643f93401c13508d8d513780e54ce9cc01203d501114be9b88d62408b8101f" -}}
{{- else if eq .chezmoi.os `windows` -}}
  {{- $ocFile = "opencode-windows-x64-baseline.zip" -}}
  {{- $ocChecksum = "cd852831bd094c2df2eb379eb98bed7a63db7f823a7caf277c732cdac33cbdb6" -}}
{{- end }}

[".local/bin/opencode{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"]
    type = "archive-file"
    url = "https://github.com/anomalyco/opencode/releases/download/v{{ $ocVersion }}/{{ $ocFile }}"
    path = "opencode{{ if eq .chezmoi.os `windows` }}.exe{{ end }}"
    executable = true
    checksum.sha256 = "{{ $ocChecksum }}"
